parameters:
  user_full_name: author 2
  links:
    - https://linkedin.com/Future-of-AI-in-Business
    - https://linkedin.com/Building-a-Strong-Professional-Network
    - https://linkedin.com/Remote-Work-and-Productivity-Hacks
    - https://medium.com/Advancements-in-Large-Language-Models
    - https://medium.com/Data-Preprocessing:-The-Foundation-of-Machine-Learning
    - https://medium.com/Building-High-Performance-APIs-with-FastAPI
    - https://github.com/AI-Powered-Chatbot-Framework
    - https://github.com/Stock-Market-Analysis-Tool
    - https://github.com/Custom-Web-Scraper-for-News-Articles
