parameters:
  user_file_name: author 1
  links:
    - https://linkedin.com/AI-Trends-2025
    - https://linkedin.com/Career-Growth-Tips
    - https://linkedin.com/Remote-Work-Productivity
    - https://medium.com/Understanding-Large-Language-Models
    - https://medium.com/Effective-Data-Preprocessing-for-ML
    - https://medium.com/Building-Scalable-APIs
    - https://github.com/Open-Source-LLM-Chatbot
    - https://github.com/Financial-Market-Analysis-Tool
    - https://github.com/Automated-Web-Scraper
